export const SCREEN_NAMES = {
  WELCOME: 'Welcome',
  ONBOARDING: 'Onboarding',
  AUTH: 'Auth',
  PLAY_CHALLENGE: 'PlayChallenge',
  CREATE_CHALLENGE: 'CreateChallenge',
  DASHBOARD: 'Dashboard',
  _AUTH: {
    SIGN_IN: 'SignIn',
    SIGN_UP: 'SignUp',
    PROFILE_SETUP: 'ProfileSetup',
  },
  _PLAY_CHALLENGE: {
    BINGO: 'Bingo',
    ENTER_WEIGHT: 'EnterWeight',
    CHAT: 'Chat',
    LEADERBOARD: 'Leaderboard',
    USERS: 'Users',
    SETTINGS: 'Settings',
  },
  _CREATE_CHALLENGE: {
    CHOOSE_PLAN: 'ChoosePlan',
    DEFINE_CHALLENGE: 'DefineChallenge',
    CARD_SETUP: 'CardSetup',
    INVITE_PARTICIPANTS: 'InviteParticipants',
    CHALLENGE_PUBLISHED: 'ChallengePublished',
  },
  _DASHBOARD: {
    ONGOING_CHALLENGE: 'OnGoingChallenge',
    ARCHIVED_CHALLENGE: 'ArchivedChallenge',
    ENTER_CODE: 'EnterCode',
    JOIN_CHALLENGE: 'JoinChallenge',
    PROFILE: 'Profile',
  },
} as const;
